In [4]:
import tensorflow as tf
tf.__version__

'2.4.1'

In [5]:
# loading mnist dataset
a=tf.random.uniform(shape=(2,2))

In [6]:
print(a)

tf.Tensor(
[[0.9946728  0.922395  ]
 [0.21829772 0.82437813]], shape=(2, 2), dtype=float32)


In [7]:
b=tf.random.uniform(shape=(2,2))

In [8]:
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7316214 , 0.39221573],
       [0.6609061 , 0.18179882]], dtype=float32)>

In [9]:
add=a+b

In [10]:
add

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.7262942, 1.3146107],
       [0.8792038, 1.006177 ]], dtype=float32)>

In [11]:
c=2.0

In [12]:
add+c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.726294 , 3.3146107],
       [2.8792038, 3.006177 ]], dtype=float32)>